# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Платформа, заданная по умолчанию
# Чтобы мы не указывали её из командной строки
default_platform(:ios)

# Описываем здесь лейны для iOS платформы
platform :ios do
  
  # Описание `lane`
  desc "Description of what the lane does"

  # Здесь указываем необходимые команды для сборки
  lane :custom_lane do
    cert
    # add actions here: https://docs.fastlane.tools/actions
  end
end
